kind: ConfigMap
apiVersion: v1
metadata:
  name: baskervillehall
data:
    READ_FROM_BEGINNING: "False"
    DEBUG_IP: "93.143.162.66"
    TOPIC_WEBLOGS: "logstash_deflect.log"
    SESSION_INACTIVITY: "5"
    GARBAGE_COLLECTION_PERIOD: "5"
    FLUSH_INCREMENT: "20"
    TOPIC_SESSIONS: "BASKERVILLEHALL_4"
    FEATURES: "request_rate,post_rate,request_interval_average,request_interval_std,response4xx_to_request_ratio,top_page_to_request_ratio,unique_path_rate,unique_path_to_request_ratio,unique_query_rate,unique_query_to_unique_path_ratio,image_to_html_ratio,js_to_html_ratio,css_to_html_ratio,path_depth_average,path_depth_std,payload_size_log_average,entropy,edge_count,static_ratio,ua_count,api_ratio,num_ciphers,num_languages,ua_score,odd_hour,hour_bucket,fingerprints_score,interval_cv,interval_consistency"
    CATEGORICAL_FEATURES: "country,primary_session,cipher,datacenter_asn,timezone"
    PCA_FEATURE: "False"
    MIN_CATEGORY_FREQUENCY: "10"
    MAX_CATEGORIES: "5"
    TOPIC_COMMANDS: "banjax_command_topic"
    TOPIC_REPORTS: "banjax_report_topic"
    NUM_PARTITIONS: "3"
    MODEL_TTL_IN_MINUTES: "300"
    DATASET_DELAY_FROM_NOW_IN_MINUTES: "10"
    S3_MODEL_STORAGE_PATH: "anton/baslervillehall/models56"
    TRAIN_BATCH_SIZE: "10"
    ACCEPTED_CONTAMINATION: "0.4"
    TRAINER_WAIT_TIME_MINUTES: "10"
    MIN_DATASET_SIZE: "50"
    SMALL_DATASET_SIZE: "500"
    NUM_SESSIONS: "5000"
    N_ESTIMATORS: "2048"
    MAX_SAMPLES: "128"
    MAX_FEATURES: "0.8"
    BOOTSTRAP: "True"
    CONTAMINATION: "0.02"
    N_JOBS: "-1"
    RANDOM_STATE: "777"
    BATCH_SIZE: "5000"
    MIN_SESSION_DURATION: "5"
    MAX_SESSION_DURATION: "3600"
    MIN_NUMBER_OF_REQUESTS : "5"
    MAX_PRIMARY_SESSIONS_PER_IP: "10"
    PRIMARY_SESSION_EXPIRATION: "10"
    DATETIME_FORMAT: "%Y-%m-%d %H:%M:%S"
    PREDICTOR_MODEL_RELOAD_IN_MINUTES: "10"
    N_JOBS_PREDICT: "10"
    WHITELIST_REFRESH_IN_MINUTES: "5"
    WHITELIST_URL_DEFAULT: "indymedia.org,splintercon.net"
    WHITELIST_IP: "https://dashboard.deflect.ca/api/add_banjax_whitelist?key=f3f7af6a8dcecc0546726f09cfaf27dd91111f8828a0ceffba9ac7ba7afcc35e"
    DEFLECT_CONFIG_URL: "https://dashboard.deflect.ca/api/baskerville_config_v2?key=d402688fd0baea4d5f10c24e739635ff2f16a6ae3791346f617ff26d1a5d656f"
    BOOTSTRAP_SERVERS: "kafka9-0.kafka9-headless.default.svc.cluster.local:9093,kafka9-2.kafka9-headless.default.svc.cluster.local:9093,kafka9-2.kafka9-headless.default.svc.cluster.local:9093"
    PENDING_TTL: "90"
    NUM_OFFENCES_FOR_DIFFICULT_CHALLENGE: "100"
    MAXSIZE_PENDING: "10000000"
    BAD_BOT_CHALLENGE: "True"
    USE_SHAPLEY: "True"
    POSTGRES_HOST: "postgres-baskervillehall.default"
    POSTGRES_PORT: "5432"
    POSTGRES_REFRESH_PERIOD_IN_SECONDS: "180"
    SENSITIVITY_FACTOR: "0.05"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "admin"
    POSTGRES_DATABASE_NAME: "baskerville"
    TTL_RECORDS_DAYS: "2"
    NUM_REQUESTS_IN_STORAGE: "7"
    SQL_TABLE_SESSIONS: "sessions"
    SQL_TABLE_COMMANDS: "challenge_command_history"
    AUTOCREATE_HOSTNAME_ID: "True"
    MAX_SESSIONS_FOR_IP: "50"
    ALERT_WEBHOOK: "https://mattermost.equalit.ie/hooks/47nd6xs1mbdmxq3y7pabcqaoco"
    ALERT_CC: '@anton'
    ALERT_WHITELIST: "[]"
    ALERT_MIN_NUM_SESSIONS: "50"
    ALERT_AGGREGATION_WINDOW_IN_MINUTES: "5"
    ALERT_DATASET_IN_HOURS: "12"
    ALERT_ZSCORE_HITS: "2.0"
    ALERT_ZSCORE_CHALLENGE_RATE: "2.2"
    ALERT_PENDING_PERIOD_IN_MINUTES: "360"
    ALERT_HOST_WHITE_LIST: ""
    ALERT_THRESHOLD_CHALLENGE_RATE: "50"
    BOT_SCORE_THRESHOLD : "0.5"
    CHALLENGE_SCRAPERS: "False"

