kind: ConfigMap
apiVersion: v1
metadata:
  name: baskervillehall
data:
    READ_FROM_BEGINNING: "False"
    DEBUG_IP: "191.96.36.197"
    TOPIC_WEBLOGS: "logstash_deflect.log"
    SESSION_INACTIVITY: "3"
    GARBAGE_COLLECTION_PERIOD: "5"
    FLUSH_INCREMENT: "10"
    TOPIC_SESSIONS: "BASKERVILLEHALL_4"
    FEATURES: "request_rate,post_rate,request_interval_average,request_interval_std,response4xx_to_request_ratio,top_page_to_request_ratio,unique_path_rate,unique_path_to_request_ratio,unique_query_rate,unique_query_to_unique_path_ratio,image_to_html_ratio,js_to_html_ratio,css_to_html_ratio,path_depth_average,path_depth_std,payload_size_log_average,entropy,edge_entropy,static_ratio"
    CATEGORICAL_FEATURES: "country"
    MIN_CATEGORY_FREQUENCY: "10"
    MAX_CATEGORIES: "5"
    TOPIC_COMMANDS: "banjax_command_topic"
    TOPIC_REPORTS: "banjax_report_topic"
    NUM_PARTITIONS: "3"
    GROUP_ID_SESSION: "baskervillehall_session"
    GROUP_ID_TRAINER: "baskervillehall_training"
    GROUP_ID_PREDICTOR: "baskervillehall_predicting2"
    MODEL_TTL_IN_MINUTES: "300"
    DATASET_DELAY_FROM_NOW_IN_MINUTES: "10"
    S3_MODEL_STORAGE_PATH: "anton/baslervillehall/models43"
    TRAIN_BATCH_SIZE: "5"
    ACCEPTED_CONTAMINATION: "0.4"
    TRAINER_WAIT_TIME_MINUTES: "10"
    MIN_DATASET_SIZE: "50"
    SMALL_DATASET_SIZE: "500"
    WARMUP_PERIOD: "1"
    NUM_SESSIONS: "5000"
    N_ESTIMATORS: "2000"
    MAX_SAMPLES: "1024"
    MAX_FEATURES: "0.8"
    CONTAMINATION: "0.03"
    N_JOBS: "1"
    RANDOM_STATE: "777"
    BATCH_SIZE: "5000"
    MIN_SESSION_DURATION: "5"
    MAX_SESSION_DURATION: "160"
    MIN_NUMBER_OF_REQUESTS : "5"
    MAX_PRIMARY_SESSIONS_PER_IP: "10"
    DATETIME_FORMAT: "%Y-%m-%d %H:%M:%S"
    PREDICTOR_MODEL_RELOAD_IN_MINUTES: "10"
    N_JOBS_PREDICT: "10"
    WHITELIST_REFRESH_IN_MINUTES: "5"
    WHITELIST_URL_DEFAULT: "indymedia.org,splintercon.net"
    WHITELIST_URL: "https://dashboard.deflect.ca/api/baskerville_config?key=f3f7af6a8dcecc0546726f09cfaf27dd91111f8828a0ceffba9ac7ba7afcc35e"
    WHITELIST_IP: "https://dashboard.deflect.ca/api/add_banjax_whitelist?key=f3f7af6a8dcecc0546726f09cfaf27dd91111f8828a0ceffba9ac7ba7afcc35e"
    BOOTSTRAP_SERVERS: "kafka9-0.kafka9-headless.default.svc.cluster.local:9093,kafka9-2.kafka9-headless.default.svc.cluster.local:9093,kafka9-2.kafka9-headless.default.svc.cluster.local:9093"
    PENDING_TTL: "30"
    MAX_OFFENCES_BEFORE_BLOCKING: "3000"
    MAXSIZE_PENDING: "10000000"
