kind: ConfigMap
apiVersion: v1
metadata:
  name: baskervillehall-ch
data:
    READ_FROM_BEGINNING: "False"
    DEBUG_IP: "191.96.36.197"
    TOPIC_WEBLOGS: "clearinghouse_logs"
    SESSION_INACTIVITY: "3"
    GARBAGE_COLLECTION_PERIOD: "3"
    FLUSH_INCREMENT: "10"
    TOPIC_SESSIONS: "clearinghouse_sessions"
    FEATURES: "request_rate,post_rate,request_interval_average,request_interval_std,response4xx_to_request_ratio,top_page_to_request_ratio,unique_path_rate,unique_path_to_request_ratio,unique_query_rate,unique_query_to_unique_path_ratio,image_to_html_ratio,js_to_html_ratio,css_to_html_ratio,path_depth_average,path_depth_std,payload_size_log_average,entropy,edge_count,static_ratio,ua_count,api_ratio,num_ciphers,num_languages,ua_score,odd_hour,hour_bucket,fingerprints_score,interval_cv,interval_consistency,rate_499,'extreme_rate_flag','high_rate_zero_entropy','bot_combo','primary_session'"
    CATEGORICAL_FEATURES: "country,cipher,datacenter_asn,timezone"
    PCA_FEATURE: "False"
    MIN_CATEGORY_FREQUENCY: "10"
    MAX_CATEGORIES: "5"
    TOPIC_COMMANDS: "clearinghouse_commands"
    TOPIC_COMMANDS_OUTPUT: "clearinghouse_commands_output"
    TOPIC_REPORTS: "banjax_report_topic"
    NUM_PARTITIONS: "3"
    MODEL_TTL_IN_MINUTES: "300"
    DATASET_DELAY_FROM_NOW_IN_MINUTES: "3"
    S3_MODEL_STORAGE_PATH: "anton/clearinghouse/models11"
    TRAIN_BATCH_SIZE: "1"
    ACCEPTED_CONTAMINATION: "0.4"
    TRAINER_WAIT_TIME_MINUTES: "10"
    MIN_DATASET_SIZE: "30"
    SMALL_DATASET_SIZE: "300"
    WARMUP_PERIOD: "1"
    NUM_SESSIONS: "5000"
    N_ESTIMATORS: "700"
    MAX_SAMPLES: "128"
    MAX_FEATURES: "0.75"
    CONTAMINATION: "0.2"
    N_JOBS: "-1"
    RANDOM_STATE: "777"
    BATCH_SIZE: "100"
    MIN_SESSION_DURATION: "7"
    MAX_SESSION_DURATION: "80"
    MIN_NUMBER_OF_REQUESTS : "8"
    MAX_PRIMARY_SESSIONS_PER_IP: "10"
    DATETIME_FORMAT: "%Y-%m-%d %H:%M:%S"
    PREDICTOR_MODEL_RELOAD_IN_MINUTES: "10"
    N_JOBS_PREDICT: "10"
    WHITELIST_REFRESH_IN_MINUTES: "5"
    WHITELIST_URL_DEFAULT: ""
    WHITELIST_URL: ""
    WHITELIST_IP: ""
    BOOTSTRAP_SERVERS: "kafka9-0.kafka9-headless.default.svc.cluster.local:9093,kafka9-2.kafka9-headless.default.svc.cluster.local:9093,kafka9-2.kafka9-headless.default.svc.cluster.local:9093"
    BOOTSTRAP_SERVERS_OUTPUT: "kafka9-0.kafka9-headless.default.svc.cluster.local:9093,kafka9-2.kafka9-headless.default.svc.cluster.local:9093,kafka9-2.kafka9-headless.default.svc.cluster.local:9093"
    PENDING_TTL: "30"
    NUM_OFFENCES_FOR_DIFFICULT_CHALLENGE: "5"
    MAXSIZE_PENDING: "10000000"
    USE_SHAPLEY: "True"
    POSTGRES_HOST: "postgres-database-service.baskerville-server-database-production"
    POSTGRES_PORT: "5432"
    POSTGRES_REFRESH_PERIOD_IN_SECONDS: "180"
    SENSITIVITY_FACTOR: "0.05"
    TTL_RECORDS_DAYS: "7"
    NUM_REQUESTS_IN_STORAGE: "20"
    SQL_TABLE_SESSIONS: "sessions"
    SQL_TABLE_COMMANDS: "challenge_command_history"
    AUTOCREATE_HOSTNAME_ID: "False"
    MAX_SESSIONS_FOR_IP: "10"
    BOT_SCORE_THRESHOLD: "0.5"
    BAD_BOT_CHALLENGE: "True"
    USE_BASKERVILLE_SCORE: "True"
    VERBOSE_CLASSIFIER: "True"


