kind: ConfigMap
apiVersion: v1
metadata:
  name: baskervillehall
data:
    READ_FROM_BEGINNING: "False"
    DEBUG_IP: "212.102.57.93"
    TOPIC_WEBLOGS: "logstash_deflect.log"
    SESSION_INACTIVITY: "3"
    GARBAGE_COLLECTION_PERIOD: "3"
    FLUSH_WINDOW_SECONDS: "60"
    TOPIC_SESSIONS: "BASKERVILLEHALL_3"
    FEATURES: "request_interval_average,num_requests,post_rate,duration,response4xx_to_request_ratio,top_page_to_request_ratio,unique_query_rate,image_to_html_ratio,js_to_html_ratio,css_to_html_ratio,path_depth_average,payload_size_log_average,entropy"
    CATEGORICAL_FEATURES: "country,primary_session"
    MIN_CATEGORY_FREQUENCY: "10"
    MAX_CATEGORIES: "5"
    TOPIC_COMMANDS: "banjax_command_topic"
    TOPIC_REPORTS: "banjax_report_topic"
    NUM_PARTITIONS: "3"
    GROUP_ID_SESSION: "baskervillehall_session"
    GROUP_ID_TRAINER: "baskervillehall_training"
    GROUP_ID_PREDICTOR: "baskervillehall_predicting2"
    MODEL_TTL_IN_MINUTES: "300"
    DATASET_DELAY_FROM_NOW_IN_MINUTES: "10"
    S3_MODEL_STORAGE_PATH: "anton/baslervillehall/models35"
    TRAIN_BATCH_SIZE: "10"
    ACCEPTED_CONTAMINATION: "0.4"
    TRAINER_WAIT_TIME_MINUTES: "10"
    MIN_DATASET_SIZE: "50"
    SMALL_DATASET_SIZE: "500"
    WARMUP_PERIOD: "1"
    NUM_SESSIONS: "50000"
    N_ESTIMATORS: "3000"
    MAX_SAMPLES: "2048"
    MAX_FEATURES: "0.9"
    CONTAMINATION: "0.01"
    N_JOBS: "1"
    RANDOM_STATE: "777"
    BATCH_SIZE: "5000"
    MIN_SESSION_DURATION: "5"
    MIN_NUMBER_OF_REQUESTS : "5"
    MAX_PRIMARY_SESSIONS_PER_IP: "10"
    DATETIME_FORMAT: "%Y-%m-%d %H:%M:%S"
    PREDICTOR_MODEL_RELOAD_IN_MINUTES: "10"
    N_JOBS_PREDICT: "10"
    WHITELIST_REFRESH_IN_MINUTES: "60"
    WHITELIST_URL_DEFAULT: "informator.ua,indymedia.org,holod.media,holod.click,holod.news,splintercon.net"
    WHITELIST_URL: "https://dashboard.deflect.ca/api/baskerville_config?key=f3f7af6a8dcecc0546726f09cfaf27dd91111f8828a0ceffba9ac7ba7afcc35e"
    WHITELIST_IP: "https://dashboard.deflect.ca/api/add_banjax_whitelist?key=f3f7af6a8dcecc0546726f09cfaf27dd91111f8828a0ceffba9ac7ba7afcc35e"
    BOOTSTRAP_SERVERS: "kafka9-0.kafka9-headless.default.svc.cluster.local:9093,kafka9-2.kafka9-headless.default.svc.cluster.local:9093,kafka9-2.kafka9-headless.default.svc.cluster.local:9093"
    PENDING_CHALLENGE_TTL_IN_MINUTES: "2"
    PASSED_CHALLENGE_TTL_IN_MINUTES: "240"
    MAXSIZE_PASSED_CHALLENGE: "10000000"
    MAXSIZE_PENDING_CHALLENGE: "10000000"

    TOPIC_COUNTER: "filebeat_deflect_access"
    GROUP_ID_COUNTER: "baskervillehall_counter"
    BOOTSTRAP_SERVERS_COUNTER: "kafkab-0.kafkab-headless.default.svc.cluster.local:9093,kafkab-2.kafkab-headless.default.svc.cluster.local:9093,kafkab-2.kafkab-headless.default.svc.cluster.local:9093"
    WINDOW_COUNTER: "1"

    PING_TOPIC: "BASKERVILLEHALL_2"
    PING_TOPIC_OUTPUT: "ping"
    PING_GROUP_ID: "baskervillehall_ping"
    PING_BOOTSTRAP_SERVERS: "kafka9-0.kafka9-headless.default.svc.cluster.local:9093,kafka9-2.kafka9-headless.default.svc.cluster.local:9093,kafka9-2.kafka9-headless.default.svc.cluster.local:9093"
    PING_HOST_REFRESH_MINUTES: "10"
    PING_NUM_WORKERS: "2"
