FROM jupyter/scipy-notebook:python-3.11.4

COPY ./requirements.txt /usr/bin/baskervillehall/requirements.txt
RUN pip install -r /usr/bin/baskervillehall/requirements.txt
RUN pip install tensorflow
COPY GoogleNews-vectors-negative300.bin /usr/bin/baskervillehall

RUN pip install gensim

COPY ./src /usr/bin/baskervillehall/src
COPY ./setup.py /usr/bin/baskervillehall/setup.py
COPY ./README.md /usr/bin/baskervillehall/README.md

USER root
WORKDIR /usr/bin/baskervillehall
RUN pip install .
RUN chmod 777 /usr/bin/baskervillehall
USER jovyan
WORKDIR /home/jovyan







