---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "baskervillehall-pinger"
  namespace: "default"
  labels:
    app: "baskervillehall-pinger"
spec:
  replicas: 3
  serviceName: "baskervillehall-pinger"
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: "baskervillehall-pinger"
  template:
    metadata:
      labels:
        app: "baskervillehall-pinger"
    spec:
      containers:
      - name: "baskervillehall-pinger"
        image: "equalitie/baskervillehall:latest"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "50m"
          limits:
            memory: "1Gi"
            cpu: "100m"
        command:
          - python
        args:
          - /usr/local/baskervillehall/src/baskervillehall/main.py
          - pinger
        envFrom:
          - configMapRef:
              name: baskervillehall
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name