apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=   #postgres
  POSTGRES_DATABASE_NAME: YmFza2VydmlsbGVfc2VydmVyX2RhdGFiYXNlX3VzZXI=   #baskerville_server_database_user
  POSTGRES_PASSWORD: dGhlcmVPbmNlV2FzQVNoaXBUaGF0UHV0VG9TZWFUaGVOYW1lT2ZUaGF0U2hpcFdhc0FCaWxseU9mVGVh   #thereOnceWasAShipThatPutToSeaTheNameOfThatShipWasABillyOfTea