---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "baskervillehall-session-ch"
  namespace: "default"
  labels:
    app: "baskervillehall-session-ch"
spec:
  replicas: 1
  serviceName: "baskervillehall-session-ch"
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: "baskervillehall-session-ch"
  template:
    metadata:
      labels:
        app: "baskervillehall-session-ch"
    spec:
      containers:
      - name: "baskervillehall-session-ch"
        image: "equalitie/baskervillehall:session"
        imagePullPolicy: Always
        command:
          - python
        args:
          - /usr/bin/baskervillehall/src/baskervillehall/main_light.py
          - session
        envFrom:
          - configMapRef:
              name: baskervillehall-ch
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name