---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "baskervillehall-session"
  namespace: "default"
  labels:
    app: "baskervillehall-session"
spec:
  replicas: 3
  serviceName: "baskervillehall-session"
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: "baskervillehall-session"
  template:
    metadata:
      labels:
        app: "baskervillehall-session"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - workers-node-6a9f33
      volumes:
        - name: bad-asn-volume
          emptyDir: {}
        - name: vpn-asn-volume
          emptyDir: { }
      initContainers:
        - name: load-bad-asn
          image: equalitie/baskervillehall_bad_asn:latest
          command: ["sh", "-c", "cp /data/bad-asn-list.csv /mnt/bad_asn/"]
          volumeMounts:
            - name: bad-asn-volume
              mountPath: /mnt/bad_asn
        - name: load-vpn-asn
          image: equalitie/baskervillehall_vpn_asn:latest
          command: ["sh", "-c", "cp -r /data/ASN-Lists /mnt/vpn_asn/"]
          volumeMounts:
            - name: vpn-asn-volume
              mountPath: /mnt/vpn_asn
      containers:
      - name: "baskervillehall-session"
        image: "equalitie/baskervillehall:latest"
        volumeMounts:
            - name: bad-asn-volume
              mountPath: /mnt/bad_asn
            - name: vpn-asn-volume
              mountPath: /mnt/vpn_asn
        imagePullPolicy: Always
        resources:
          requests:
            memory: "5Gi"
            cpu: "250m"
          limits:
            memory: "20Gi"
            cpu: "2000m"
        command:
          - python
        args:
          - /usr/bin/baskervillehall/src/baskervillehall/main.py
          - session
        envFrom:
          - configMapRef:
              name: baskervillehall
        env:
        - name: BAD_ASN_FILE
          value: "/mnt/bad_asn/bad-asn-list.csv"
        - name: VPN_ASN_PATH
          value: "/mnt/vpn_asn/ASN-Lists"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name