---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "baskervillehall-session"
  namespace: "default"
  labels:
    app: "baskervillehall-session"
spec:
  replicas: 9
  serviceName: "baskervillehall-session"
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: "baskervillehall-session"
  template:
    metadata:
      labels:
        app: "baskervillehall-session"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - workers-node-6a9f33
      volumes:
        # Bad ASN volume disabled
        # - name: bad-asn-volume
        #   emptyDir: {}
        # VPN ASN volume disabled
        # - name: vpn-asn-volume
        #   emptyDir: { }
      initContainers:
        # Bad ASN database disabled to save disk space
        # - name: load-bad-asn
        #   image: equalitie/baskervillehall_bad_asn:latest
        #   command: ["sh", "-c", "cp /data/bad-asn-list.csv /mnt/bad_asn/"]
        #   volumeMounts:
        #     - name: bad-asn-volume
        #       mountPath: /mnt/bad_asn
        # VPN ASN database disabled to save disk space
        # - name: load-vpn-asn
        #   image: equalitie/baskervillehall_vpn_asn:latest
        #   command: ["sh", "-c", "cp -r /data/ASN-Lists /mnt/vpn_asn/"]
        #   volumeMounts:
        #     - name: vpn-asn-volume
        #       mountPath: /mnt/vpn_asn
      containers:
      - name: "baskervillehall-session"
        image: "equalitie/baskervillehall:session"
        volumeMounts:
            # Bad ASN volume mount disabled
            # - name: bad-asn-volume
            #   mountPath: /mnt/bad_asn
            # VPN ASN volume mount disabled
            # - name: vpn-asn-volume
            #   mountPath: /mnt/vpn_asn
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "50m"
          limits:
            memory: "20Gi"
            cpu: "2000m"
        command:
          - python
        args:
          - /usr/bin/baskervillehall/src/baskervillehall/main_light.py
          - session
        envFrom:
          - configMapRef:
              name: baskervillehall
        env:
        # Bad ASN file disabled
        # - name: BAD_ASN_FILE
        #   value: "/mnt/bad_asn/bad-asn-list.csv"
        # VPN ASN path disabled
        # - name: VPN_ASN_PATH
        #   value: "/mnt/vpn_asn/ASN-Lists"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name