---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "baskervillehall-session-debug"
  namespace: "default"
  labels:
    app: "baskervillehall-session-debug"
spec:
  replicas: 3
  serviceName: "baskervillehall-session-debug"
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: "baskervillehall-session-debug"
  template:
    metadata:
      labels:
        app: "baskervillehall-session-debug"
    spec:
      containers:
      - name: "baskervillehall-session-debug"
        image: "equalitie/baskervillehall:debug"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "5Gi"
            cpu: "250m"
          limits:
            memory: "20Gi"
            cpu: "2000m"
        command:
          - python
        args:
          - /usr/bin/baskervillehall/src/baskervillehall/main.py
          - session
        envFrom:
          - configMapRef:
              name: baskervillehall-debug
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name