---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "baskervillehall-storage-ch"
  namespace: "default"
  labels:
    app: "baskervillehall-storage-ch"
spec:
  replicas: 1
  serviceName: "baskervillehall-storage-ch"
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: "baskervillehall-storage-ch"
  template:
    metadata:
      labels:
        app: "baskervillehall-storage-ch"
    spec:
      restartPolicy: Always
      containers:
      - name: "baskervillehall-storage-ch"
        image: "equalitie/baskervillehall:session_dev"
        imagePullPolicy: Always
        command:
          - python
        args:
          - /usr/bin/baskervillehall/src/baskervillehall/main_light.py
          - storage
        envFrom:
          - configMapRef:
              name: baskervillehall-ch
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-baskervillehall-dev-secret
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-baskervillehall-dev-secret
              key: password
        - name: POSTGRES_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-baskervillehall-dev-secret
              key: database
