---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "baskervillehall-storage-ch"
  namespace: "default"
  labels:
    app: "baskervillehall-storage-ch"
spec:
  replicas: 3
  serviceName: "baskervillehall-storage-ch"
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: "baskervillehall-storage-ch"
  template:
    metadata:
      labels:
        app: "baskervillehall-storage-ch"
    spec:
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - workers-node-eac0c8
                      - workers-node-c83aa9
      containers:
      - name: "baskervillehall-storage-ch"
        image: "equalitie/baskervillehall:latest"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "300m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        command:
          - python
        args:
          - /usr/bin/baskervillehall/src/baskervillehall/main.py
          - storage
        envFrom:
          - configMapRef:
              name: baskervillehall-ch
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DATABASE_NAME
