apiVersion: v1
kind: Service
metadata:
  name: postgres-baskervillehall
  labels:
    app: postgres-baskervillehall
spec:
  selector:
    app: postgres-baskervillehall
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432