apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-baskervillehall-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi