apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-baskervillehall-pvc
spec:
  storageClassName: retain-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi