apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-baskervillehall-pv
  labels:
    type: local
spec:
  storageClassName: csi-expandable
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"