apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-baskervillehall-pv
  labels:
    type: local
spec:
  storageClassName: csi-cinder-high-speed
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"