apiVersion: v1
kind: Pod
metadata:
  name: pg-copy
spec:
  restartPolicy: Never
  containers:
    - name: rsync
      image: alpine:3.20
      command: ["/bin/sh","-c"]
      args: ["apk add --no-cache rsync; rsync -aHAX --info=progress2 /old/ /new/"]
      volumeMounts:
        - { name: old, mountPath: /old }
        - { name: new, mountPath: /new }
  volumes:
    - name: old
      persistentVolumeClaim:
        claimName: postgres-baskervillehall-pvc
    - name: new
      persistentVolumeClaim:
        claimName: postgres-baskervillehall-pvc2
