apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-admin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-cinder-high-speed-gen2