{
 "title": "Maxi",
 "tags": [ "working" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Host", "query": "%" }
  ]
 },
 "panels": [
  {
   "title": "Hits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(session_end,$__interval),\n  sum(hits) AS \"id\",\n  host_name as \"host\"\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' \nGROUP BY 1,3\nORDER BY 1"
    }
   ]
  },
  {
   "title": "IP",
   "type": "stat",
   "description": "The total number of challenged IPs",
   "gridPos": { "h": 10, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct ip)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "stat",
   "description": "The total number of challenged IPs",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(hits) AS \"hits\"\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(session_end,$__interval),\n  count(ip_cookie) AS \"id\",\n  host_name as \"host\"\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' \nGROUP BY 1,3\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "description": "The total number of challenged IPs",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct ip_cookie)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Bot/Human",
   "type": "graph",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(session_end,$__interval),\n  count(distinct ip_cookie) AS \"id\",\n  CASE\n    when human = 1 then 'human'\n    when human = 0 then 'bot'\n   END as \"human\"\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%'\nGROUP BY 1,3\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Bot Rate",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select (SELECT\n  count(distinct ip)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and human<>1) * 100.0 / \n(\n(SELECT\n  count(distinct ip)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%')\n)"
    }
   ]
  },
  {
   "title": "VPN Rate",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select (SELECT\n  count(distinct ip_cookie)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and vpn=1 and human=1) * 100.0 / \n(\n(SELECT\n  count(distinct ip_cookie)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and human = 1 and host_name like '%${Host}%')\n)"
    }
   ]
  },
  {
   "title": "VPN",
   "type": "graph",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(session_end,$__interval),\n  count(distinct ip_cookie) AS \"id\",\n  CASE\n    when vpn = 1 then 'vpn'\n    when vpn = 0 then 'regular'\n   END as \"vpn\"\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and human = 1\nGROUP BY 1,3\nORDER BY 1"
    }
   ]
  },
  {
   "title": "AI Bot Rate",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select (SELECT\n  count(distinct ip_cookie)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and class = 'ai_bot' and host_name like '%${Host}%' and human=0) * 100.0 / \n(\n(SELECT\n  count(distinct ip_cookie)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%')\n)"
    }
   ]
  },
  {
   "title": "Total Chalalenge Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select (SELECT\n  count(distinct ip_cookie)\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%') * 100.0 / \n(\n(SELECT\n  count(distinct ip_cookie)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%')\n)"
    }
   ]
  },
  {
   "title": "Block Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select (SELECT\n  count(distinct ip_address)\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and command_type_name like '%block_ip%' and host_name like '%${Host}%') * 100.0 / \n(\n(SELECT\n  count(distinct ip)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%')\n)"
    }
   ]
  },
  {
   "title": "Bot class",
   "type": "graph",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(session_end,$__interval),\n  count(distinct ip_cookie) AS \"id\",\n  class\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and class <> 'human'\nGROUP BY 1,3\nORDER BY 3"
    }
   ]
  },
  {
   "title": "Scraper",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(session_end,$__interval),\n  count(distinct ip_cookie) AS num_sessions,\n  case when scraper_name = '' then 'xxx' else concat(host_name, '_',  scraper_name) end \nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and scraper_name <> ''\nGROUP BY 1,3\nHAVING count(distinct ip_cookie) > 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "IF + AE Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select (SELECT\n  count(distinct ip_cookie)\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and meta='') * 100.0 / \n(\n(SELECT\n  count(distinct ip_cookie)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%')\n)"
    }
   ]
  },
  {
   "title": "AE + IF #",
   "type": "stat",
   "description": "The total number of challenged IPs",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct ip_cookie)\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and meta = ''\n"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(session_end,$__interval),\n  count(distinct ip_cookie) AS \"id\",\n  command_type_name\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' \nGROUP BY 1,3\nORDER BY 3"
    }
   ]
  },
  {
   "title": "IF Rate Bot",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select (SELECT\n  count(distinct ip_cookie)\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and meta='' and human <>1 and prediction_if = 1) * 100.0 / \n(\n(SELECT\n  count(distinct ip_cookie)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%')\n)"
    }
   ]
  },
  {
   "title": "AE Rate Bot",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select (SELECT\n  count(distinct ip_cookie)\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and meta='' and human <>1 and prediction_ae = 1) * 100.0 / \n(\n(SELECT\n  count(distinct ip_cookie)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%')\n)"
    }
   ]
  },
  {
   "title": "IF Rate Human",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select (SELECT\n  count(distinct ip_cookie)\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and meta='' and human = 1 and prediction_if = 1) * 100.0 / \n(\n(SELECT\n  count(distinct ip_cookie)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%')\n)"
    }
   ]
  },
  {
   "title": "AE Rate Bot",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select (SELECT\n  count(distinct ip_cookie)\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and meta='' and human  = 1 and prediction_ae = 1) * 100.0 / \n(\n(SELECT\n  count(distinct ip_cookie)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%')\n)"
    }
   ]
  },
  {
   "title": "Challenge - Model",
   "type": "graph",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(session_end,$__interval),\n  count(distinct ip_cookie) AS \"id\",\n  host_name as \"host\"\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and meta = ''\nGROUP BY 1,3\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Meta Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select (SELECT\n  count(distinct ip_cookie)\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and meta <> '') * 100.0 / \n(\n(SELECT\n  count(distinct ip_cookie)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%')\n)"
    }
   ]
  },
  {
   "title": "Meta #",
   "type": "stat",
   "description": "The total number of challenged IPs",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct ip_address)\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and meta <> ''\n"
    }
   ]
  },
  {
   "title": "Challenge - Human/Bot",
   "type": "graph",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(session_end,$__interval),\n  count(distinct ip_cookie) AS \"id\",\n  CASE\n    when human = 1 then 'human'\n    when human = 0 then 'bot'\n   END as \"human\"\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' \nGROUP BY 1,3\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Meta ",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct ip_cookie) as num,\n  meta\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and meta <> ''\ngroup by 2 order by num desc"
    }
   ]
  },
  {
   "title": "Challenge Rate - Model Total",
   "type": "graph",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select A.time, A.host, num_challenged *100.0 / num_sessions as \"challenge_rate\" from\n (\nSELECT\n  $__timeGroupAlias(session_end,$__interval),\n  count(distinct ip_cookie) AS \"num_challenged\",\n  host_name as \"host\"\nFROM challenge_command_history cch\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and meta = ''\nGROUP BY 1,3 \n) as A inner join (\n\n\tSELECT\n\t  $__timeGroupAlias(session_end,$__interval),\n\t  count(distinct ip_cookie) AS \"num_sessions\",\n\t  host_name as \"host\"\n\tFROM sessions\n\tWHERE\n\t  $__timeFilter(session_end) and host_name like '%${Host}%'\n\tGROUP BY 1,3\n\t\n) as B on A.time=B.time and A.host=B.host where num_sessions > 10 order by time;\n"
    }
   ]
  },
  {
   "title": "Challenge Rate - Meta",
   "type": "graph",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select A.time, A.host, num_challenged *100.0 / num_sessions as \"challenge_rate\" from\n (\nSELECT\n  $__timeGroupAlias(session_end,$__interval),\n  count(distinct ip_cookie) AS \"num_challenged\",\n  host_name as \"host\"\nFROM challenge_command_history cch\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and (meta <> '')\nGROUP BY 1,3 \n) as A inner join (\n\n\tSELECT\n\t  $__timeGroupAlias(session_end,$__interval),\n\t  count(distinct ip_cookie) AS \"num_sessions\",\n\t  host_name as \"host\"\n\tFROM sessions\n\tWHERE\n\t  $__timeFilter(session_end) and host_name like '%${Host}%'\n\tGROUP BY 1,3\n\t\n) as B on A.time=B.time and A.host=B.host where num_sessions > 50 order by time;\n"
    }
   ]
  },
  {
   "title": "Passed",
   "type": "stat",
   "description": "The total number of challenged IPs",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count (distinct ip_cookie)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and passed_challenge = 1 and host_name like '%${Host}%'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Meta Total",
   "type": "graph",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(session_end,$__interval),\n  count(distinct ip_cookie) AS \"num_challenged\",\n  meta as \"meta\"\nFROM challenge_command_history cch\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and meta <> ''\nGROUP BY 1,3"
    }
   ]
  },
  {
   "title": "Passed challenge",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(session_end,$__interval),\n  count(distinct ip_cookie) AS \"id\", \n  host_name as host\nFROM sessions \nWHERE\n  $__timeFilter(session_end)\n  and passed_challenge = 1 and host_name like '%${Host}%'\nGROUP BY 1,3\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Passed Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select (SELECT\n  count(distinct ip_address)\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and passed_challenge = 1 and host_name like '%${Host}%') * 100.0 / \n(\n(SELECT\n  count(distinct ip_address)\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end)  and host_name like '%${Host}%')\n)"
    }
   ]
  },
  {
   "title": "High Bot Score Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select (SELECT\n  count(distinct ip_cookie)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and passed_challenge = 1 and host_name like '%${Host}%' and bot_score > 0.5 and bot_score_top_factor <> 'no_payload' ) * 100.0 / \n(\n(SELECT\n  count(distinct ip_cookie)\nFROM sessions\nWHERE\n  $__timeFilter(session_end) and passed_challenge = 1 and host_name like '%${Host}%')\n)"
    }
   ]
  },
  {
   "title": "High Bot Score",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(session_end,$__interval),\n  count(distinct ip_cookie) AS \"id\",\n  bot_score_top_factor\nFROM sessions \nWHERE\n  $__timeFilter(session_end)\n  and passed_challenge = 1 and host_name like '%${Host}%'\n  and bot_score > 0.5 and bot_score_top_factor <> 'err_payload' and bot_score_top_factor <> 'no_payload'\nGROUP BY 1,3\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Shapley",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct ip_cookie) as num,\n  shapley_feature\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and meta = ''\ngroup by 2 order by num desc"
    }
   ]
  },
  {
   "title": "Shapley IF",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(session_end,$__interval),\n  count(distinct ip_cookie) AS \"id\",\n  shapley_feature_if as \"host\"\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and meta = ''\nGROUP BY 1,3\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Shapley  AE",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(session_end,$__interval),\n  count(distinct ip_cookie) AS \"id\",\n  shapley_feature_ae as \"host\"\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' and meta = ''\nGROUP BY 1,3\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Fingerprints",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(session_end,$__interval),\n  count(distinct ip_cookie) AS num_sessions,\n  case when fingerprints is null then 'xxx' else concat(host_name, '_',  fingerprints) end \nFROM sessions\nWHERE\n  $__timeFilter(session_end) and host_name like '%${Host}%' \nGROUP BY 1,3\nHAVING count(distinct ip_cookie) > 10\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Challenges",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '${Host}' \nlimit 1000"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM challenge_command_history\nWHERE\n  $__timeFilter(session_end) and host_name like '${Host}' and command_type_name like '%block_ip%'\nlimit 1000"
    }
   ]
  }
 ]
}